### ISSUE TITLE
How to add new PATH to bash and zsh

### ISSUE THREAD

**Issue by ghost** [happy-hacking-linux/dotfiles#1]
I've installed Arch using your iso, and it's good.

The problem is that I want to add $HOME/bin as path so dmenu, i3, and other programs can execute scripts and programs from there.

Currently, only shell from terminal(zsh AND bash) can execute those in $HOME/bin, but not dmenu, or i3 config.

So, how can i add PATH?

**Comment by azer** [comment]
Can you try adding;

```
 export PATH=~/bin:$PATH
 ```

to the top of the .zprofile, restart X and let me know how it goes ?

**Comment by ghost** [comment]
Yes, I will try.

EDIT: It worked, thank you for you kind help.
